apiVersion: v1
kind: PersistentVolume
metadata:
  name: mondo-db-volume
  labels:
    volume: mondo-db-volume
spec:
  capacity:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mongodb-volume
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-volume-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: mondo-db-volume
