apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    volume: mysql-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/export"
    type: DirectoryOrCreate
