apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
      app: frontend-app
      tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
   matchLabels:
    app: frontend-app
    tier: frontend
    track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-app
        tier: frontend
        track: stable
    spec:
      containers:
        - name: front
          image: jeezzy/front-back-app:latest
          ports:
            - containerPort: 80
