apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo"
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        command: ["mongod", "-replSet", "rs0"]
        volumeMounts:
        - mountPath: /data/db
          name: mondo-db-volume
        ports:
        - containerPort: 27017
          name: peer
        volumeMounts:
          - name: mondo-db-volume
            mountPath: "/data/db"
      volumes:
        - name: mondo-db-volume
          persistentVolumeClaim:
             claimName: mongo-db-volume-claim
