apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: my-grafana
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'test-site'
        static_configs:
          - targets: ['test-site-service.default.svc.cluster.local:9113']
      - job_name: 'nginx-example'
        static_configs:
          - targets: ['alpaca-service.default.svc.cluster.local:9113']
      - job_name: 'bandicoot'
        metrics_path: /metrics
        static_configs:
          - targets: ['bandicoot-service.default.svc.cluster.local:8080']
      - job_name: 'contour-controller'
        metrics_path: /metrics
        static_configs:
          - targets: ['contour.projectcontour.svc.cluster.local:8000']
      - job_name: 'contour-envoy'
        metrics_path: /stats/prometheus
        static_configs:
          - targets: ['envoy.projectcontour.svc.cluster.local:8002']
