apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: my-grafana
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'alpaca-prod'
        static_configs:
          - targets: ['alpaca.example.com']
      - job_name: 'test-site'
        static_configs:
          - targets: ['test-site.example.com']
      - job_name: 'nginx-example'
        static_configs:
          - targets: ['nginx.example.com']
      - job_name: 'bandicoot'
        static_configs:
          - targets: ['bandicoot.example.com']
